import { type NextRequest, NextResponse } from "next/server"
import { sql } from "@vercel/postgres"
import { jsPDF } from "jspdf"

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const resumeId = searchParams.get("resumeId")

    if (!resumeId) {
      return NextResponse.json({ error: "Resume ID required" }, { status: 400 })
    }

    // Check if user has premium access
    const hasPremiumCookie = request.cookies.get("atsPremium")?.value === "true"

    if (!hasPremiumCookie) {
      return NextResponse.json({ error: "Premium access required" }, { status: 403 })
    }

    // Get resume and analysis from database
    const result = await sql`
      SELECT "fileName", "analysisCache"
      FROM resume_uploads
      WHERE id = ${resumeId}
      LIMIT 1
    `

    if (result.rows.length === 0) {
      return NextResponse.json({ error: "Resume not found" }, { status: 404 })
    }

    const { fileName, analysisCache } = result.rows[0]
    const analysis = analysisCache as any

    if (!analysis) {
      return NextResponse.json({ error: "No analysis found for this resume" }, { status: 404 })
    }

    // Generate PDF using jsPDF
    const doc = new jsPDF()

    // Header
    doc.setFontSize(20)
    doc.setTextColor(10, 26, 47)
    doc.text("ATS Resume Analysis Report", 105, 20, { align: "center" })

    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(`Resume: ${fileName}`, 105, 28, { align: "center" })
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 33, { align: "center" })

    doc.setFontSize(8)
    doc.setTextColor(120, 120, 120)
    const disclaimer = doc.splitTextToSize(
      "AI-Powered Analysis – This report is generated by AI and may contain inaccuracies. Always review and customize before submitting to employers.",
      170,
    )
    doc.text(disclaimer, 105, 38, { align: "center" })

    // ATS Score
    doc.setFontSize(16)
    doc.setTextColor(10, 26, 47)
    doc.text(`ATS Score: ${analysis.score}%`, 20, 50)

    // Score interpretation
    doc.setFontSize(10)
    doc.setTextColor(60, 60, 60)
    const interpretation =
      analysis.score >= 80
        ? "Excellent! Your resume is well-optimized for ATS systems."
        : analysis.score >= 60
          ? "Good start, but there's room for improvement."
          : "Your resume needs significant optimization to pass ATS filters."
    doc.text(interpretation, 20, 57)

    let yPos = 70

    // Missing Keywords
    doc.setFontSize(14)
    doc.setTextColor(10, 26, 47)
    doc.text("Missing Keywords", 20, yPos)
    yPos += 7

    doc.setFontSize(9)
    doc.setTextColor(60, 60, 60)
    analysis.keywords.missing.forEach((keyword: string, idx: number) => {
      if (yPos > 270) {
        doc.addPage()
        yPos = 20
      }
      doc.text(`• ${keyword}`, 25, yPos)
      yPos += 5
    })

    yPos += 5

    // Formatting Issues
    doc.setFontSize(14)
    doc.setTextColor(10, 26, 47)
    doc.text("Formatting Issues", 20, yPos)
    yPos += 7

    doc.setFontSize(9)
    doc.setTextColor(60, 60, 60)
    analysis.formatting.forEach((issue: any) => {
      if (yPos > 270) {
        doc.addPage()
        yPos = 20
      }
      doc.text(`• [${issue.severity.toUpperCase()}] ${issue.issue}`, 25, yPos)
      yPos += 5
    })

    yPos += 5

    // Optimization Tips
    doc.setFontSize(14)
    doc.setTextColor(10, 26, 47)
    doc.text("Optimization Tips", 20, yPos)
    yPos += 7

    doc.setFontSize(9)
    doc.setTextColor(60, 60, 60)
    analysis.tips.forEach((tip: string) => {
      if (yPos > 270) {
        doc.addPage()
        yPos = 20
      }
      const lines = doc.splitTextToSize(`• ${tip}`, 170)
      doc.text(lines, 25, yPos)
      yPos += lines.length * 5
    })

    // Section Breakdown (if available)
    if (analysis.sections && analysis.sections.length > 0) {
      if (yPos > 240) {
        doc.addPage()
        yPos = 20
      }

      yPos += 5
      doc.setFontSize(14)
      doc.setTextColor(10, 26, 47)
      doc.text("Section Breakdown", 20, yPos)
      yPos += 7

      doc.setFontSize(9)
      doc.setTextColor(60, 60, 60)
      analysis.sections.forEach((section: any) => {
        if (yPos > 270) {
          doc.addPage()
          yPos = 20
        }
        doc.text(`${section.name}: ${section.score}%`, 25, yPos)
        yPos += 5
      })
    }

    // Job Alignment (if available)
    if (analysis.jobAlignment) {
      yPos += 5
      doc.setFontSize(14)
      doc.setTextColor(10, 26, 47)
      doc.text(`Job Role Alignment: ${analysis.jobAlignment}%`, 20, yPos)
    }

    // Footer with disclaimer
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text("Generated by STAR Workforce Solutions - www.starworkforcesolutions.com", 105, 285, {
      align: "center",
    })

    doc.setFontSize(7)
    const footerDisclaimer = doc.splitTextToSize(
      "AI-Powered Analysis – This report is generated by AI and may contain inaccuracies. Always review and customize before submitting to employers.",
      190,
    )
    doc.text(footerDisclaimer, 105, 290, { align: "center" })

    // Generate PDF buffer
    const pdfBuffer = Buffer.from(doc.output("arraybuffer"))

    const originalName = fileName.replace(/\.[^/.]+$/, "")

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${originalName}_STAR_Optimizer_Report.pdf"`,
      },
    })
  } catch (error: any) {
    console.error("[ERROR REPORT] PDF Export Error:", error)
    return NextResponse.json(
      {
        error: "PDF generation failed",
        details: error?.message || String(error),
        code: error?.code,
      },
      { status: 500 },
    )
  }
}
