export const STRIPE_PRICES = {
  ATS_OPTIMIZER: process.env.STRIPE_PRICE_ATS_OPTIMIZER!,
  COVER_LETTER: process.env.STRIPE_PRICE_COVER_LETTER!,
  RESUME_DISTRIBUTION: process.env.STRIPE_PRICE_RESUME_DISTRIBUTION!,
  DIY_PREMIUM: process.env.STRIPE_PRICE_DIY_PREMIUM!,
  RECRUITER_BASIC: process.env.STRIPE_PRICE_RECRUITER_BASIC!,
  RECRUITER_STANDARD: process.env.STRIPE_PRICE_RECRUITER_STANDARD!,
  RECRUITER_PRO: process.env.STRIPE_PRICE_RECRUITER_PRO!,
} as const;

export const STRIPE_PRODUCTS = {
  ATS_OPTIMIZER: process.env.STRIPE_PRODUCT_ATS_OPTIMIZER!,
  COVER_LETTER: process.env.STRIPE_PRODUCT_COVER_LETTER!,
  RESUME_DISTRIBUTION: process.env.STRIPE_PRODUCT_RESUME_DISTRIBUTION!,
  DIY_PREMIUM: process.env.STRIPE_PRODUCT_DIY_PREMIUM!,
  RECRUITER_BASIC: process.env.STRIPE_PRODUCT_RECRUITER_BASIC!,
  RECRUITER_STANDARD: process.env.STRIPE_PRODUCT_RECRUITER_STANDARD!,
  RECRUITER_PRO: process.env.STRIPE_PRODUCT_RECRUITER_PRO!,
} as const;
