import { type NextRequest, NextResponse } from "next/server"
import { sql } from "@vercel/postgres"

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const coverLetterId = searchParams.get("coverLetterId")

    if (!coverLetterId) {
      return NextResponse.json({ error: "Cover Letter ID required" }, { status: 400 })
    }

    const result = await sql`
      SELECT job_description, resume_filename
      FROM cover_letter_uploads
      WHERE id = ${coverLetterId}
      LIMIT 1
    `

    if (result.rows.length === 0) {
      return NextResponse.json({ error: "Cover letter not found" }, { status: 404 })
    }

    // In production, generate actual PDF. For now, return placeholder text
    const pdfContent = `STAR Workforce Solutions - Cover Letter

AI-Generated Content Disclaimer:
This cover letter was generated by AI and should be reviewed and customized before submission.

[Full cover letter content would be rendered here as PDF]

---
Generated by STAR Workforce Solutions
www.starworkforcesolutions.com
AI-Powered Career Tools`

    const blob = new Blob([pdfContent], { type: "text/plain" })

    return new NextResponse(blob, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="cover_letter.pdf"`,
      },
    })
  } catch (error: any) {
    console.error("[ERROR] Cover Letter Export Error:", error)
    return NextResponse.json(
      {
        error: "Export failed",
        details: error?.message || String(error),
      },
      { status: 500 },
    )
  }
}
